name: Copy Post welcome comment exec on push 
on:
  push:
    branches: 
      - welcome-workflow
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-slim
    steps:
      - run: echo "Welcome!"