name: Copy Post welcome comment workflowdispatch
on:
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  welcome:
    name: Post welcome comment
    runs-on: ubuntu-slim
    steps:
      - run: echo "Welcome!"